name: meta
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cmake
  - qhull
  - boost
  - vtk==9.2.6
  - itk==5.3.0
  - libitk
  - libitk-devel
  - numpy
  - nibabel
  - pandas
  - pyvista
  - scipy
  - tqdm
  - tslearn
  - dipy
  - pip:
      - pyradiomics>=3.1.0
