# This is configuration file addapted from pyradiomics
# https://github.com/AIM-Harvard/pyradiomics/tree/master/examples/exampleSettings
# https://pyradiomics.readthedocs.io/en/latest/customization.html#radiomics-parameter-file-label
# https://pyradiomics.readthedocs.io/en/v3.0.1/features.html

# Image types to use: "Original" for unfiltered image, "Wavelet" for wavelet filtered image, "LoG" for Laplacian of Gaussian filtered image.
imageType:
  Original: {}
  
featureClass:
  firstorder:
    - Energy
    - TotalEnergy
    - Minimum
    - 10Percentile
    - 90Percentile
    - Maximum
    - Mean
    - Median
    - InterquartileRange
    - Range
    - MeanAbsoluteDeviation
    - RobustMeanAbsoluteDeviation
    - RootMeanSquared
    - StandardDeviation
    - Skewness
    - Kurtosis
    - Variance
  shape:
    - MeshVolume
    - VoxelVolume
    - SurfaceArea
    - SurfaceVolumeRatio
    - Sphericity
    - Maximum3DDiameter
    - Maximum2DDiameterSlice
    - Maximum2DDiameterColumn
    - Maximum2DDiameterRow
    - MajorAxisLength
    - MinorAxisLength
    - LeastAxisLength
    - Elongation
    - Flatness

setting:
  ## Image Normalization
  normalize:
  normalizeScale:
  removeOutliers:
  ## Image discretization
  label: 1
  # binWidth: 150 